### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by DefianceQ** [Gevorian/Apex-Legends#1]
Not sure where to place this but just wanted to put it in here in case it helps anyone.
I snatched this today and added it to the correct folders but it crashed my PC whenever I tried to launch the game, turned out updating my Nvidia graphics card drivers sorted it out, so if anyone has that issue, try updating.

**Comment by shotloof** [comment]
hello, i need a thumb neck i create my own autoexec from yours i will not publish at all i tell you a big thanks for this release but i would have wanted to know if it had a launch order or i can make the shadows with the shadows set them with the parameters etc etc thank you for the patience you had to read this in a big thank you
