### ISSUE TITLE
No inventory

### ISSUE THREAD

**Issue by T3h-vICE** [Gevorian/Apex-Legends#2]
Hi,
first of all: Awesome script!
Problem:
Since the start of season 2, i have the problem that sometimes the inventory is completly empty. I need to swap weapons and then it works on the 3rd try or so. It rarely happens, that the whole HUD is gone and sometimes the menuoutlines are flickering.

**Comment by anderslam** [comment]
I'm having the same problem I would reccomend removing all exec stuff and
repair game an add things back slowly to figure out out or wait for new
support wish I knew more.
